[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "nodejs", "postgresql"]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd backend && python -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"