[phases.setup]
aptPkgs = ["libpq-dev"]

[phases.install]
cmds = ["cd frontend && npm install", "cd ../backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "python3 -m uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
